/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventanas;

import consultas.ConsulStock;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author FELIX
 */
public class GestionarStock extends javax.swing.JFrame {

    /**
     * Creates new form GestionarInventario
     */
    public GestionarStock() {
        initComponents();

        setSize(1280, 670);
        setResizable(false);
        setLocationRelativeTo(null);
        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);

        //Mostrando Stock
        Mostrar("");
        lbl_producto.setText("TODOS");
        Informacion("");
    }
    
    private void OcultarColumnas() {
        tab_stock.getColumnModel().getColumn(0).setMaxWidth(0);
        tab_stock.getColumnModel().getColumn(0).setMinWidth(0);
        tab_stock.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
    
    private void Mostrar(String buscar) {
        try {
            DefaultTableModel modelo;
            ConsulStock func = new ConsulStock();
            modelo = func.mostrar(buscar);
            tab_stock.setModel(modelo);
            OcultarColumnas();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al mostrar stock");
            System.err.println("Error al mostrar stock: " + e);
        }
    }
    
    private void Informacion(String buscar) {
        try {
            HashMap info;
            ConsulStock func = new ConsulStock();
            info = func.info(buscar);
            lbl_compras.setText(info.get("Compras").toString());
            lbl_ventas.setText(info.get("Ventas").toString());
            lbl_utilidad.setText(info.get("Utilidad").toString());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error al mostrar stock");
            System.err.println("Error al mostrar stock: " + e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel_Info = new javax.swing.JPanel();
        lbl_compras = new javax.swing.JLabel();
        lbl_ventas = new javax.swing.JLabel();
        lbl_utilidad = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbl_producto = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jPanel_Stock = new javax.swing.JPanel();
        btn_actualizar = new javax.swing.JButton();
        jScrollPane_stock = new javax.swing.JScrollPane();
        tab_stock = new javax.swing.JTable();
        btn_exportarStock = new javax.swing.JButton();
        txt_id_producto = new javax.swing.JTextField();
        txt_producto = new javax.swing.JTextField();
        btn_buscar_producto = new javax.swing.JButton();
        btn_todos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gestionar Inventario");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("GESTION DE INVENTARIO - SAITO INVENTORY");
        jLabel1.setOpaque(true);
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 80));

        jPanel_Info.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Info.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), "Información Actual", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel_Info.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_compras.setBackground(new java.awt.Color(220, 20, 60));
        lbl_compras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_compras.setForeground(new java.awt.Color(255, 255, 255));
        lbl_compras.setText("lbl_compras");
        lbl_compras.setOpaque(true);
        jPanel_Info.add(lbl_compras, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, 160, 40));

        lbl_ventas.setBackground(new java.awt.Color(46, 139, 87));
        lbl_ventas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_ventas.setForeground(new java.awt.Color(255, 255, 255));
        lbl_ventas.setText("lbl_ventas");
        lbl_ventas.setOpaque(true);
        jPanel_Info.add(lbl_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 290, 160, 40));

        lbl_utilidad.setBackground(new java.awt.Color(100, 149, 237));
        lbl_utilidad.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_utilidad.setForeground(new java.awt.Color(255, 255, 255));
        lbl_utilidad.setText("lbl_utilidad");
        lbl_utilidad.setOpaque(true);
        jPanel_Info.add(lbl_utilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 160, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("$");
        jPanel_Info.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 340, 30, 40));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Ventas:");
        jPanel_Info.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, -1, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Utilidad:");
        jPanel_Info.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 40));

        lbl_producto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lbl_producto.setText("lbl_producto");
        jPanel_Info.add(lbl_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, -1, 40));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Producto:");
        jPanel_Info.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, -1, 40));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Compras:");
        jPanel_Info.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 240, -1, 40));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("$");
        jPanel_Info.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 290, 30, 40));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("$");
        jPanel_Info.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 30, 40));

        jPanel1.add(jPanel_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 620, 540));

        jPanel_Stock.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Stock.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 4, true), "Stock disponible", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 24))); // NOI18N
        jPanel_Stock.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_actualizar.setText("Actualizar");
        btn_actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_actualizarActionPerformed(evt);
            }
        });
        jPanel_Stock.add(btn_actualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        tab_stock.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tab_stock.setEnabled(false);
        tab_stock.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tab_stockMouseClicked(evt);
            }
        });
        jScrollPane_stock.setViewportView(tab_stock);

        jPanel_Stock.add(jScrollPane_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 580, 440));

        btn_exportarStock.setText("Exportar");
        btn_exportarStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exportarStockActionPerformed(evt);
            }
        });
        jPanel_Stock.add(btn_exportarStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 100, -1));

        txt_id_producto.setEnabled(false);
        jPanel_Stock.add(txt_id_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 40, -1));

        txt_producto.setEnabled(false);
        jPanel_Stock.add(txt_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, 110, 20));

        btn_buscar_producto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/buscar.png"))); // NOI18N
        btn_buscar_producto.setOpaque(false);
        btn_buscar_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_buscar_productoActionPerformed(evt);
            }
        });
        jPanel_Stock.add(btn_buscar_producto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 40, 40));

        btn_todos.setText("Todo");
        btn_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_todosActionPerformed(evt);
            }
        });
        jPanel_Stock.add(btn_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, -1));

        jPanel1.add(jPanel_Stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 90, 620, 540));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_buscar_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_buscar_productoActionPerformed
        // TODO add your handling code here:
        BuscarProducto.tipo_transaccion = "";
        BuscarProducto form = new BuscarProducto();
        form.setVisible(true);
    }//GEN-LAST:event_btn_buscar_productoActionPerformed

    private void btn_exportarStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exportarStockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_exportarStockActionPerformed

    private void btn_actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_actualizarActionPerformed
        // TODO add your handling code here:
        Mostrar(txt_id_producto.getText());
    }//GEN-LAST:event_btn_actualizarActionPerformed

    private void btn_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_todosActionPerformed
        // TODO add your handling code here:
        Mostrar("");
        lbl_producto.setText("TODOS");
        Informacion("");
    }//GEN-LAST:event_btn_todosActionPerformed

    private void tab_stockMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tab_stockMouseClicked
        // TODO add your handling code here:
        int fila = tab_stock.rowAtPoint(evt.getPoint());
        txt_id_producto.setText(tab_stock.getValueAt(fila, 0).toString());
        txt_producto.setText(tab_stock.getValueAt(fila, 1).toString());
        lbl_producto.setText(txt_producto.getText());
        Informacion(txt_id_producto.getText());
    }//GEN-LAST:event_tab_stockMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionarStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionarStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_actualizar;
    private javax.swing.JButton btn_buscar_producto;
    private javax.swing.JButton btn_exportarStock;
    private javax.swing.JButton btn_todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Info;
    private javax.swing.JPanel jPanel_Stock;
    private javax.swing.JScrollPane jScrollPane_stock;
    private javax.swing.JLabel lbl_compras;
    private javax.swing.JLabel lbl_producto;
    private javax.swing.JLabel lbl_utilidad;
    private javax.swing.JLabel lbl_ventas;
    private javax.swing.JTable tab_stock;
    public static javax.swing.JTextField txt_id_producto;
    public static javax.swing.JTextField txt_producto;
    // End of variables declaration//GEN-END:variables
}
